// Tikets
export const SEND_TICKET_INFO = 'SEND_TICKET_INFO';
export const SEND_TICKET_INFO_SUCCESS = 'SEND_TICKET_INFO_SUCCESS';
export const SEND_TICKET_INFO_FAILURE = 'SEND_TICKET_INFO_FAILURE';
export const SELECT_CELL = 'SELECT_CELL';
export const GENERATE_WIN_COMBINATIONS = 'GENERATE_WIN_COMBINATIONS';
